name: Deploy to github pages

on:
    workflow_dispatch:
    push:
        branches: ['main']

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: 'pages'
    cancel-in-progress: true

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
            - name: Build
              run: |
                  git clone https://github.com/${{ github.repository }} .
                  git checkout ${{ github.sha }}
                  curl https://mise.run | sh
                  eval "$(mise activate bash --shims)"
                  mise use node
                  npm clean-install
                  BASE="/${{ github.event.repository.name }}" npm run build
                  tar -cv --file "./artifact.tar" -C ./dist/ .
            - name: Upload
              uses: actions/upload-artifact@v4
              with: { name: 'github-pages', path: './artifact.tar' }
            - name: Deploy
              uses: actions/deploy-pages@v4
              id: deployment
